In [5]:
# import numpy
# create array x
import numpy as np
x= [4,3,2,6.5,21,53,77,88,23,11,1,2]
x= np.array(x)
x

array([  4. ,   3. ,   2. ,   6.5,  21. ,  53. ,  77. ,  88. ,  23. ,
        11. ,   1. ,   2. ])

In [6]:
# print the shape of x
x.shape

(12,)

In [9]:
# create a two dimensional array
x_2d = x.reshape(3,4)
x_2d

array([[  4. ,   3. ,   2. ,   6.5],
       [ 21. ,  53. ,  77. ,  88. ],
       [ 23. ,  11. ,   1. ,   2. ]])

In [10]:
# print shape of 2d array
x_2d.shape

(3, 4)

In [23]:
# reshape the array to 2 x 6
x_2d_2x6= x_2d.reshape(2,6)
x_2d_2x6

array([[  4. ,   3. ,   2. ,   6.5,  21. ,  53. ],
       [ 77. ,  88. ,  23. ,  11. ,   1. ,   2. ]])

In [27]:
# reshape the array to 1 x 12
x_2d_2x6= x_2d.reshape(1,12)
x_2d_2x6

array([[  4. ,   3. ,   2. ,   6.5,  21. ,  53. ,  77. ,  88. ,  23. ,
         11. ,   1. ,   2. ]])

In [34]:
# transpose the array

t=x_2d_2x6.T

In [20]:
# indexing method 1
x[np.array([2, 5, 1, 2])]

array([  2.,  53.,   3.,   2.])

In [33]:
# indexing method 2
x_2d_2x6[0][2]

2.0

In [37]:
# indexing method 3
t[6][0]

77.0

In [41]:
# indexing method 4
x=np.arange(44).reshape(22,2)
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43]])

In [11]:
# indexing method 5

In [10]:
# indexing method 6